Feat/#27 mp 1
HyunjeLee/Scrap-2024 pull request #29
Opened 2024-05-05 01:32 UTC by HyunjeLee

## 📍 PR 타입 (하나 이상 선택)
- [ ] 기능 추가
- [ ] 버그 수정
- [ ] 코드 리팩토링 or 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정

## ❗️ 관련 이슈 링크
- #27 

## 📌 개요
- 

## 🔁 변경 사항

## 📸 구현 화면 스크린샷
<img src="https://github.com/HyunjeLee/Scrap-2024/assets/101737272/b24e16f8-9f0b-4ab4-b821-3a2fd029962e" width="300" height="651">

## 👀 기타 더 이야기해볼 점

## ✅ 체크 리스트
- [ ] PR 템플릿에 맞추어 작성했어요.
- [ ] 변경 내용에 대한 테스트를 진행했어요.
- [ ] 프로그램이 정상적으로 동작해요.
- [ ] PR에 적절한 라벨을 선택했어요.
- [ ] 불필요한 코드는 삭제했어요.
- [ ] 담당자를 할당했어요.
- [ ] 리뷰어를 할당했어요.
- [ ] android:exported 속성 확인

2024-05-05 06:38 UTC, choign3123 requested changes
수정 부탁드립니다.

2024-05-05 06:38 UTC, choign3123 commented on app/src/main/res/layout/fragment_mypage.xml
> +        tools:ignore="TouchTargetSizeCheck,TextContrastCheck,TextSizeCheck" />
제가 수정한 브랜치 봐주세요. **브랜치명: feat/MP-1-GANA**
기본적으로 constrain layout을 사용했을때 가운데 정렬은 "update: 스크랩 카운트 위치 조정" 처럼 하는겁니다.
안그러면 화면에 따라 가운데 정렬이 깨져요.
<비교본>
"수정 후"
![image](https://github.com/HyunjeLee/Scrap-2024/assets/87647534/17d37693-484c-444a-bdb1-bcb69cd60e22)
"수정 전"
![image](https://github.com/HyunjeLee/Scrap-2024/assets/87647534/eff46c86-6a68-4a9c-98d5-9d3c839c5c5b)
이전까진 여기까지 확인은 안했었어서, 다른 화면에서도 이런식으로 가운데 정렬했던게 있다면 다 수정해주세요.

2024-05-05 06:44 UTC, choign3123 requested changes
배경색과 탑바 색상 구분이 안되어있습니다. 수정 부탁드립니다.

2024-05-05 06:47 UTC, choign3123 commented on app/src/main/res/layout/fragment_mypage.xml
> +        tools:ignore="TouchTargetSizeCheck,TextContrastCheck,TextSizeCheck" />
그리고 **"update: mypage 위치값 조정"** 커밋도 봐주세요.
margin을 TOP에서 줘버리면, 나중에 textScrapCount y 위치값 수정할 때 imageBackgroundCount, textNotice marginTop값 다 수정해야 하는 문제가 발생합니다.

2024-05-15 05:39 UTC, HyunjeLee commented
추후 구현

2024-05-15 05:39 UTC, closed without merging